<?php
/**
 * Theme setup.
 *
 * @package woptimize-theme
 */

defined( 'ABSPATH' ) || exit;

/**
 * Register theme support.
 *
 * @return void
 */
function woptimize_theme_setup() {
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support(
		'html5',
		array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' )
	);
}
add_action( 'after_setup_theme', 'woptimize_theme_setup' );

/**
 * Enqueue the design tokens, then the theme stylesheet on top of them.
 *
 * assets/css/tokens.css is generated by `npm run tokens:build` at the repo root
 * and is gitignored. It is never hand-edited. Missing file means the token build
 * has not run — see packages/design-tokens/README.md.
 *
 * @return void
 */
function woptimize_theme_enqueue_assets() {
	$tokens_relative = 'assets/css/tokens.css';
	$tokens_path     = get_theme_file_path( $tokens_relative );
	$dependencies    = array();

	if ( file_exists( $tokens_path ) ) {
		wp_enqueue_style(
			'woptimize-tokens',
			get_theme_file_uri( $tokens_relative ),
			array(),
			(string) filemtime( $tokens_path )
		);

		$dependencies[] = 'woptimize-tokens';
	}

	wp_enqueue_style(
		'woptimize-theme',
		get_stylesheet_uri(),
		$dependencies,
		wp_get_theme()->get( 'Version' )
	);
}
add_action( 'wp_enqueue_scripts', 'woptimize_theme_enqueue_assets' );
